In [1]:
import rpy2.robjects as ro

In [2]:
print(ro.r)

<rpy2.robjects.R object at 0x1079e1460>
platform: x86_64-apple-darwin17.0
arch: x86_64
os: darwin17.0
system: x86_64, darwin17.0
status:
major: 4
minor: 2.1
year: 2022
month: 06
day: 23
svn rev: 82513
language: R
version.string: R version 4.2.1 (2022-06-23)
nickname: Funny-Looking Kid

In [5]:
from rpy2.robjects.packages import importr

In [ ]:
base = importr('base')
utils = importr('utils')
robyn = importr('reticulate')
robyn = importr('Robyn')

In [14]:
ro.globalenv['dat'] = utils.read_csv('robyn_lum_input.csv')

In [15]:
utils.data('dt_simulated_weekly')

<rpy2.robjects.vectors.StrVector object at 0x10cc465c0> [RTYPES.STRSXP]
R classes: ('character',)
['dt_simulated_weekly']

In [16]:
base.source('robyn_lum_script.R')

R[write to console]: 'hyperparameters' are not provided yet. To include them, run robyn_inputs(InputCollect = InputCollect, hyperparameters = ...)

<rpy2.robjects.vectors.ListVector object at 0x10cc591c0> [RTYPES.VECSXP]
R classes: ('list',)
[ListSexpVector, BoolSexpVector]
  value: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x10cc59680> [RTYPES.VECSXP]
  visible: <class 'rpy2.rinterface.BoolSexpVector'>
  <rpy2.rinterface.BoolSexpVector object at 0x10cc59080> [RTYPES.LGLSXP]

In [18]:
base.ls()

<rpy2.robjects.vectors.StrVector object at 0x10cca2ec0> [RTYPES.STRSXP]
R classes: ('character',)
['InputColl..., 'dat', 'dt_simula..., 'hyperpara...]

In [19]:
ro.r['InputCollect']

<rpy2.robjects.vectors.ListVector object at 0x10cc76240> [RTYPES.VECSXP]
R classes: ('robyn_inputs', 'list')
[ListSexpV..., ListSexpV..., NULLType, NULLType, ..., StrSexpVe..., NULLType, NULLType, ListSexpV...]
<rpy2.robjects.vectors.ListVector object at 0x10cc76240> [RTYPES.VECSXP]
R classes: ('robyn_inputs', 'list')
[ListSexpV..., ListSexpV..., NULLType, NULLType, ..., StrSexpVe..., NULLType, NULLType, ListSexpV...]
<rpy2.robjects.vectors.ListVector object at 0x10cc76240> [RTYPES.VECSXP]
R classes: ('robyn_inputs', 'list')
[ListSexpV..., ListSexpV..., NULLType, NULLType, ..., StrSexpVe..., NULLType, NULLType, ListSexpV...]
  dt_mod: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x107327380> [RTYPES.NILSXP]
  dt_modRollWind: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x107327380> [RTYPES.NILSXP]
...
  date_var: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x10cc4f4c0> [RTYPES.STRSXP]
R classes: ('character',)
['geometric']
  dayInterval: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x107327380> [RTYPES.NILSXP]
  intervalType: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x107327380> [RTYPES.NILSXP]
<rpy2.robjects.vectors.ListVector object at 0x10cc76240> [RTYPES.VECSXP]
R classes: ('robyn_inputs', 'list')
[ListSexpV..., ListSexpV..., NULLType, NULLType, ..., StrSexpVe..., NULLType, NULLType, ListSexpV...]

In [20]:
ro.r('''
Sys.setenv(R_FUTURE_FORK_ENABLE="true")
options(future.fork.enable = TRUE)
''')

<rpy2.robjects.vectors.BoolVector object at 0x10b805cc0> [RTYPES.LGLSXP]
R classes: ('logical',)
[       1]

In [21]:
ro.r('''
options(future.fork.enable = TRUE)
''')

<rpy2.robjects.vectors.ListVector object at 0x10c7a6cc0> [RTYPES.VECSXP]
R classes: ('list',)
[NULLType]
  future.fork.enable: <class 'rpy2.rinterface_lib.sexp.NULLType'>
  <rpy2.rinterface_lib.sexp.NULLType object at 0x107327380> [RTYPES.NILSXP]

In [22]:
base.source('run_model.R')

Total Observations: 214 (weeks)
Input Table Columns (14):
  Date: DATE
  Dependent: TP_LUMINOUS_SALES_VALUE [revenue]
  Paid Media: TV_LUMINOUS_TRP, GL_LUMINOUS_IMPRESSIONS, FB_LUMINOUS_IMPRESSIONS, DV_LUMINOUS_IMPRESSIONS
  Paid Media Spend: TV_LUMINOUS_SPEND, GL_LUMINOUS_SPEND, FB_LUMINOUS_SPEND, DV_LUMINOUS_SPEND
  Context: TP_LUMINOUS_AVG_PRICE, TP_COLGATE_NOAD_AVG_PRICE, TP_COMPETITORS_AVG_PRICE, TP_COMPETITORS_SALES_VALUE
  Organic:
  Prophet (Auto-generated): trend, season, holiday on MX
  Unused:

Date Range: 2018-01-22:2022-02-21
Model Window: 2018-01-22:2022-02-21 (214 weeks)
With Calibration: FALSE
Custom parameters: None

Adstock: geometric
Hyper-parameters for media transformations:
  TV_LUMINOUS_SPEND_alphas: [0.5, 3]
  TV_LUMINOUS_SPEND_gammas: [0.3, 1]
  TV_LUMINOUS_SPEND_thetas: [0, 0.3]
  GL_LUMINOUS_SPEND_alphas: [0.5, 3]
  GL_LUMINOUS_SPEND_gammas: [0.3, 1]
  GL_LUMINOUS_SPEND_thetas: [0, 0.3]
  FB_LUMINOUS_SPEND_alphas: [0.5, 3]
  FB_LUMINOUS_SPEND_gammas: [0.3, 1]
  FB_LUMINOUS_SPEND_thetas: [0, 0.3]
  DV_LUMINOUS_SPEND_alphas: [0.5, 3]
  DV_LUMINOUS_SPEND_gammas: [0.3, 1]
  DV_LUMINOUS_SPEND_thetas: [0, 0.3]

R[write to console]: Input data has 214 weeks in total: 2018-01-22 to 2022-02-21

R[write to console]: Initial model is built on rolling window of 214 week: 2018-01-22 to 2022-02-21

R[write to console]: Using geometric adstocking with 13 hyperparameters (13 to iterate + 0 fixed) on 8 cores

R[write to console]: >>> Starting 5 trials with 2000 iterations each using TwoPointsDE nevergrad algorithm...

R[write to console]:   Running trial 1 of 5

  |                                                                      |   0%

:

: